### PR TITLE
Update to gradle 3.1.1

### PR DESCRIPTION
**Pull request by kaytat**
Remove use of enforceUniquePackageName

Use variants.output.all to update the filename with the version

Tidy up style reference

### CODE REVIEW

**Comment by kaytat** [comment]
I don't actually know what enforceUniquePackageName does.  I just removed it to fix an error.

Also, although the variant filename remains the same, this new gradle version seems to put it in a different directory.  FYI.

**Comment by nelenkov** [comment]
Thanks for the PR.

Have you verified that you can build wwwjdic-app and wwwjdic-app-donate (different package), with this change. enforceUniquePackageName was used to migrate from library projects, AFAIK. 

The whole thing can be merged into a few variants, but I haven't gotten around to it..

**Comment by kaytat** [comment]
I used Android Studio's Build -> Build APKs command to build both wwjdic-app-debug-2.4.1.apk and wwjdic-app-donate-debug-2.4.1.apk.

I then pulled both of those APKs back into Android Studio and verified that the manifest does in fact have two different package names:

package="org.nick.wwwjdic"
and
package="org.nick.wwwjdic.donate"

respectively.

I couldn't build the release since I don't have access to "nick.keystore"

**Comment by kaytat** [comment]
I'm finding I want to clean this up a little more.  I'm going to consolidate some of the settings into the top level project.

**Pull request closed without merging**
